### ISSUE TITLE
[CZ] UI knihovna implementace

### ISSUE THREAD

**Issue by JarekParal** [RoboticsBrno/Esp32-RBGridUI#1]
Issue pro řešení implementace UI knihovny.

https://github.com/RoboticsBrno/RB3201-RBControl-Roboruka-library/blob/b9f9fa7a0509b27057d3d9aa84868ce4519af9d9/src/ui/ui.cpp#L17

Související issue: [UI knihovna API](https://github.com/RoboticsBrno/roboruka-dev/issues/1)

**Comment by Tasssadar** [comment]
Souhlasím, to jsou dobré nápady - udělám to tak :)

BTW, napadá někoho jak udělat Builder pattern tak, abych nemusel všechno psát ručně pro každý typ? Myslím, že templaty na to napasovat nejdou(?) a když to bude v nějakém společném rodiči, tak to bude vracet referenci na jiný typ. https://github.com/RoboticsBrno/Esp32-RBGridUI/blob/master/src/builder/button.h#L11 (cc @yaqwsx )

**Comment by yaqwsx** [comment]
@Tasssadar Nejsem si jist, co přesně máš na mysli. Chceš mít např. metody `onPress` a `css` vyčleněné do třídy, ze které chceš dědit? Pokud ano, tak přesně na to slouží vzor, kterému se říká CRTP. V podstatě:

```.cpp
template < typename Self > 
class Pressable {
public:
	// This have to be in every CRTP/Mixin class
	Self& self() { return *static_cast< Self * >( this ); }
	const Self& self() const { return *static_cast< Self * >( this ); }

	// Then you can implement whatever you like - even reference
    // members & functions from child class - just call them via self().method()

	Self& onPress( std::function< void() > callback ) {
		_callback = callback();
		self().updateSettings(); // example of calling child method
		return self();
	}

	std::function< void() > _callback;
};

// When you want to use it:
class Button: public Pressable< Button > {
    void updateSettings() {
		std::cout << "We have just update the settings!\n";
	}
};

// Then you can call:
Button b;
b.onPress( []{} );
```

A dokonce se i základní třídy mohou odkazovat na jiné třídy. V postatě tímto docílíš mixinů z Javascriptu. Snad do C++23/26 přibude feature zvaná "deducig this", která umožní tyto věci psát hezčeji a čitelněji: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0847r2.html

**Comment by yaqwsx** [comment]
BTW: Koukám, že v tom článku, který jsem poslal je přímo uveden příklad na builder pattern pro C++17 (http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0847r2.html#builder-pattern)

**Comment by Tasssadar** [comment]
Jo, přesně tohle je ono. Pokoušel jsem se to takhle udělat, ale skončilo to na tom, že [je pak nedostanu do vectoru](https://ideone.com/LgKC7d), protože díky té šabloně nemají společnou třídu :/

EDIT: použiju na to [dědění z více tříd zároveň](https://ideone.com/LjslAs), to vypadá schůdně.

**Comment by yaqwsx** [comment]
Ano, to je feature CRTP - také se mu občas říká "statický polymorfismus". Jsou to vlastně mixiny - kusy implementace rozprostřené mezi vícero tříd.

To navržené řešení z JSONable je za mě správné.
