### ISSUE TITLE
[CZ] Druhy widgetů

### ISSUE THREAD

**Issue by Tasssadar** [RoboticsBrno/Esp32-RBGridUI#2]
- [x] Bar
- [x] Button
- [x] Joystick
- [x] LED
- [x] Ruka (z roboruky)
- [x] Slider
- [x] Switch (checkbox)
- [x] Text
- [x] Input

**Comment by cednik** [comment]
- [ ] bargraf
- [x] slider
- [ ] color picker
- [ ] graf
- [ ] canvas? (A když se rozjedu, tak s eventy onClick, vracející souřadnice, swipe, zoom, rotate, ... :-D )

**Comment by JarekParal** [comment]
Ok aneb Lorris Toolbox?

**Comment by cednik** [comment]
Ano, akorát script možná můžeme vynechat :-)

**Comment by Tasssadar** [comment]
Implementoval jsem všechny widgety vypsané v prvním postu, přijde mi to jako dostatečný základ. Pro další rozšiřující widgety prosím samostatnou issue nebo pull request :)
